### ISSUE TITLE
Rewrite on Apache ?

### ISSUE THREAD

**Issue by liberodark** [SuperPWA/Super-Progressive-Web-Apps#108]
Hi,

Have install your plugin but im using apache not nginx.
This is your fix for the worker on nginx.
```
rewrite ^/superpwa-manifest(-[0-9]+)?.json$ /index.php?superpwa-manifest-$1.json last;
rewrite ^/OneSignalSDKWorker.js.php$ /index.php?OneSignalSDKWorker.js-$1.php last;
rewrite ^/superpwa-sw(-[0-9]+)?.js$ /index.php?superpwa-sw.js last;
```

But what is it on apache ?
Have try this but not work.
```
RewriteRule ^/superpwa-manifest(-[0-9]+)?.json$ /index.php?superpwa-manifest-$1.json last;
RewriteRule ^/OneSignalSDKWorker.js.php$ /index.php?OneSignalSDKWorker.js-$1.php last;
RewriteRule ^/superpwa-sw(-[0-9]+)?.js$ /index.php?superpwa-sw.js last;
```

Best Regards

**Comment by Sanjeevsetu** [comment]
Hi @liberodark 

Extremely sorry for the late response.

Its been long time when you first created the ticket. Since than our plugin has improved a lot. You should try our latest version. Need more help contact us here https://superpwa.com/contact/ or create a new ticket as I am closing this ticket.
