### ISSUE TITLE
URL of the site is shown on the top of the Android application

### ISSUE THREAD

**Issue by AnupriyaSurapaneni** [SuperPWA/Super-Progressive-Web-Apps#179]
Sometimes, the website URL is displayed on the top of the Android application(downloaded from Google play store) even after uploading the assetslink.json file.
Reference - https://secure.helpscout.net/conversation/1470795293/188718?folderId=4074390

**Comment by syedimran22** [comment]
Regarding the issue of URL is rendering at top of your app issue  you can follow the below tutorial

1. Update your asset links file for production
💁🏽‍♀️ Heads up:

This step is required for running the production version of your app. If you skip this step, your app will crash or will a browser address bar will appear inside your app. See our asset links helper for more info.

Once you've uploaded your .aab file, Google Play re-signs your app. Because of this, you'll need to update your asset links file.

To update your asset links and remove the address bar from your app, login to the Google Play Console, select your app, then choose Setup -> App integrity, then copy your SHA-256 fingerprint:

https://github.com/pwa-builder/CloudAPK/raw/master/static/google-play-signing.png

Then, paste the fingerprint into your assetlinks.json file:

[
{
"relation": ...,
"target": {
"namespace": ...,
"package_name": ...,
"sha256_cert_fingerprints": [
"...",
"PASTE YOUR NEW SHA-256 FINGERPRINT HERE"
]
}
}
]
Once your updated assetlinks.json file is deployed to your server, the address bar will disappear from your app.
