### ISSUE TITLE
[Feature Request] Custom Backstack

### ISSUE THREAD

**Issue by raveesh-me** [SuperPWA/Super-Progressive-Web-Apps#21]
Web back stacks are not like chrome back button. This creates some difference in the experience when pressing the back button. Can a way be implemented so that we can have a custom backstack, based on the sitemap?

**Comment by josevarghese** [comment]
I didn't get a clear idea about your request. So can you please elaborate it. 

Thanks,
Jose

**Comment by raveesh-me** [comment]
Yup, when making a native app, back button acts as 'up'. But within web browsers, back button behaves as 'back'. Suppose I went through these steps within the PWA ->
* Touch Logo to go home
* Select a Post
* Select next read another Post
* Go to Home by touching the logo

Here, pressing back should close the app, but we will have to press the back button 3-4 times before pwa exits. This is a difference between native and chrome experience, and I feel PWAs should have custom back stacks where pressing home pops all the median states from the stack.

I know this is not a feature that can be implemented immediately, however, this is something that'd be awesome!

**Comment by arunbasillal** [comment]
Hello @raveesh-me 

Thanks for sharing more details. As you know there is no native way to do this because even though it behaves like an app, its still an extension of the browser. 

I have added this to our feature list under user requested features. I am also going to close this for now because its not something we plan on implementing in the short term. We will of course revisit this and update you as we work on it. 

Thanks again.
