### ISSUE TITLE
Need to add QR code feature in SuperPWA.

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#255]
Need to add QR code feature in SuperPWA, where user can scan code then PWA should install in his mobile.
As one user said this feature will be a game-changer for his clients.

Ref: https://secure.helpscout.net/conversation/1810683728/229979?folderId=1060556.

**Comment by syedimran22** [comment]
Released in SuperPWA Version : 2.2.3 & SuperPWA PRO Version : 1.16

**Comment by tobyy22** [comment]
Hi, I bought the PRO version and the QR code works only as a link to the site. Is there a possibility to actually install the PWA through the QR code so that the user doesn't need to go through the process of adding the application to home screen? Or at least give a prompt to the user asking whether the PWA can be added to the home screen? 
Thanks
