### ISSUE TITLE
Error 500 on backend

### ISSUE THREAD

**Issue by bilyboy785** [SuperPWA/Super-Progressive-Web-Apps#26]
Hi !

We've got an 500 error on Backend, i disabled plugin temporarely but need to fix this .. 

```
2018/04/23 11:15:12 [error] 29813#29813: *1436033 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once({my-path}/wp-content/plugins/super-progressive-web-apps/admin/loader.php): failed to open stream: No such file or directory in {my-path}/wp-content/plugins/super-progressive-web-apps/superpwa.php on line 61
PHP message: PHP Fatal error:  require_once(): Failed opening required '{my-path}/wp-content/plugins/super-progressive-web-apps/admin/loader.php' (include_path='.:/usr/share/php') in {my-path}/wp-content/plugins/super-progressive-web-apps/superpwa.php on line 61" while reading response header from upstream, client: 105.102.84.199, server: frenchmac.com, request: "GET /wp-admin/admin-ajax.php?action=wpp_get_popular&id=12 HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php7.0-fpm/web21.sock:", host: "frenchmac.com", referrer: "https://frenchmac.com/mac/sauvegarder-iphone-disque-dur-externe/"
``` 

We use last version of the plugin

Can you help us ?

**Comment by arunbasillal** [comment]
Copy of https://wordpress.org/support/topic/error-500-on-backend/

@bilyboy785 

Was this an upgrade? Or a new install?
From the error it looks like the files were not downloaded correctly. Can you try again?

**Comment by bilyboy785** [comment]
I read after that you dont help for support here, so i wrote on Wordpress.org.

It was already installed for few days. I tried to delete the folder and reupload plugin from zip archive on Wordpress Plugin Market, and it's the same, 500 error.

**Comment by arunbasillal** [comment]
Sorry about that, its just a note to remind users to use the WordPress support forum instead of raising questions here (rather than issues real issues). What you have is a real issue. 

Regarding the issue, specifically this part: 

```PHP Warning:  require_once({my-path}/wp-content/plugins/super-progressive-web-apps/admin/loader.php): failed to open stream: No such file or directory in {my-path}/wp-content/plugins/super-progressive-web-apps/superpwa.php on line 61```

There is no line 61 in the current release as you can see here: https://github.com/SuperPWA/Super-Progressive-Web-Apps/blob/master/superpwa.php. Its a total of 58 lines. The previous versions had line 61 and this is a reference to the loader. You can check the code here: https://github.com/SuperPWA/Super-Progressive-Web-Apps/releases/tag/1.5

I am not an expert on this, but can this be related to FastCGI cache? Can you flush the cache and see if that helps?

**Comment by arunbasillal** [comment]
Sweet deal! Glad that worked and I learned something new :)

I will leave a quick reply on WordPress.org as well, just so that it might help someone in the future.
