### ISSUE TITLE
Offline page never shows, even when offline

### ISSUE THREAD

**Issue by glueckpress** [SuperPWA/Super-Progressive-Web-Apps#30]
## Environment
- PHP 7.2
- latest WordPress with _WP Rocket_ page caching and file optimisation
- Setting _Start Page_: `— Homepage —` (https://glueckpress.com/)
- Setting _Offline Page_: https://glueckpress.com/you-appear-to-be-offline/

## Test:
- Open home page in Chrome (incognito) with emulated mobile phone (browser caches cleared, service worker updated)
- Set network throttling to _Offline_
- Open for example https://glueckpress.com/9336/amp-and-wordpress/
- **Expected behaviour: show _Offline Page_**
- **Factual behaviour: shows content of home page under the URL of the post**
- Same behaviour with and without page caching/file optimisation
- Same behaviour on a real smartphone (Galaxy S6, Chrome)

Let me know if you need me to test further, or if I missed anything!

**Comment by arunbasillal** [comment]
Hello Caspar! What a pleasure to see you here. Glad to see you testing out our humble project. 

Here is my experience: https://youtu.be/3SivfBPr9os and as you can see the offline page is working as expected. 

My theory: Your browser cache already have the default offline page from the time you tested the website with the default offline page. The old offline page that is cached might be the one still being served. 

I tested this out by changing the offline page (or my test install) once the service worker was installed on my browser and the offline page did not update. 

Short term fix: Clear the browser cache as below (sorry if you already know this): 

![delete cache storage](https://user-images.githubusercontent.com/5751474/39409078-50a09720-4bfe-11e8-96b2-b4d7520a5da8.png)

Long term fix would be to detect this in the service worker and update as necessary. Or a more efficient process would be to change the cache version as user updates the settings. Right now the cache version changes with each update of the plugin and the new offline page and other dependencies will be cached again with each update. 

Let me know if that was the case and if the short term fix helped. Also feedback + experience sharing is most welcome wherever you find most appropriate. I look forward to it :)

**Comment by glueckpress** [comment]
@arunbasillal Thanks for the video and explanation! Good to see the page worked. 😉 

> My theory: Your browser cache already have the default offline page from the time you tested the website with the default offline page.

I don’t think so, I usually have _Disable cache_ on when dev tools are open. I also made sure to clear the complete storage on the _Application_ panel.

I unchecked _Disable cache_ for testing here, but made sure the cache was empty.

https://www.youtube.com/watch?v=3euwARKCE7A

However, the fact the page appeared for you seems to indicate the issue is on my end—even though it seems curios I had the same behaviour on my phone.

**Comment by arunbasillal** [comment]
Interesting. In my original reply I had a poor choice of word. By browser cache I meant, cache storage. Doesn't make the theory any better and your reply video disproves it. 

I followed the steps from your video precisely (incognito window, Galaxy S5, clicked "clear site data" and reloaded the homepage). At 0:27 of the video - https://youtu.be/3euwARKCE7A?t=27s you have a shot of the cache storage. 

Here is how mine looks: 

![cache storage](https://user-images.githubusercontent.com/5751474/39410207-fbfa0f26-4c11-11e8-9266-203faf3fb1bf.PNG)

See how mine has the `you-appear-to-be-offline/` page in the cache storage? 

Another difference is the console window. Right after `SuperPWA service worker caching dependencies` it usually lists the dependencies as you can see here:

![02](https://user-images.githubusercontent.com/5751474/39410259-eadce460-4c12-11e8-8766-bdb1e5209b76.PNG)

Really strange. 

Long shot: 
- Can you check inside the file `superpwa-sw-1.js` from the console window to see if we have the right offline page in there. (I am sure it will be there, because then it will be too easy. lol)
- Another long shot, clear the site data and close the incognito tab (Chrome removes the unregistered service workers when the tab is closed). 

Wish I had a better idea, but this is honestly the first time I am coming across such a case. Sorry if its frustrating.

**Comment by glueckpress** [comment]
You we’re actually right in your first theory! The service worker got loaded _from disk cache_ for me, no matter what data I delete in dev tools:

<img width="916" alt="screen shot 2018-04-30 at 08 23 36" src="https://user-images.githubusercontent.com/308422/39416835-607b834c-4c50-11e8-82ce-367fdc13cfda.png">

And when I opened that actual (local) file, it showed this outdated setting (while the SW file on my server showed the correct offline page URL):
```json
const offlinePage='https://glueckpress.com';
```

I had closed the incognito window and deleted all application storage multiple times up to here. Apparently the SW file that got stored first still survived.

Same on my phone: I went to Chrome settings and did a full _Clear and Reset_, yet the behaviour stayed the same.

I’ve now opened the site for the first time in a different browser (Vivaldi, relies on Chrome engine), and even there the SW file is loaded _from disk cache_! I had not used that browser in months time! 

<img width="1001" alt="screen shot 2018-04-30 at 08 38 11" src="https://user-images.githubusercontent.com/308422/39417060-030b5154-4c52-11e8-88bf-57996c8f00bb.png">

## Summary

What did the trick for me was:

- deactivate the plugin
- remove the SW files from my server
- clear browser storage
- visit the site _without_ the plugin being active
- activate the plugin again

Now the correct SW file is loaded in Chrome/desktop. 

I was not able to get the updated SW file loaded on my phone, even though I cleared and reset the settings and storage for the site:

![screenshot_20180430-083242](https://user-images.githubusercontent.com/308422/39417666-290e375a-4c56-11e8-9abb-1750619656f2.png)

The behaviour seems related to browser settings/behaviour, so I assume this issue can be closed. Whether or not something can or should be done to tell the browser to update SW files stored in disk cache is above my current knowledge. If possible, it seems desirable, though.

**Comment by arunbasillal** [comment]
Oh wow, what happened in `Vivaldi` is beyond what I can explain at the moment. Strange things indeed. 

If you hadn't closed the window I would have pointed you to this comment (sharing now just FYI and for someone else reading this) - https://github.com/react-boilerplate/react-boilerplate/issues/645#issuecomment-230979776

There is a feature in our current roadmap to add query strings (or encode versions) so as to bust browser cache and other caches if any for the service worker. Issues like this will not happen again when that is finally done. Closing the issue since that is already in the plans.
