### ISSUE TITLE
 Bug with network-first cache strategy and REST calls

### ISSUE THREAD

**Issue by Sdaud1950** [SuperPWA/Super-Progressive-Web-Apps#329]
Bug with network-first cache strategy and REST calls

Ref ticket. https://magazine3.in/conversation/54732?folder_id=29 
Ref screenshot. https://prnt.sc/QfcgsF27Sdxf

**Comment by dwise85** [comment]
The nutshell of the issue is that my custom client-side code is making REST calls. I set Super PWA to be network-first, then cache, but due to the logic today, it only uses the specified setting for network first for `e.request.mode === "navigation"`. However, the REST calls are made as `e.request.mode === "cors"`.

The cors calls are thus hitting the fallback handling, which is a cache-first strategy. This breaks my website as it can continue to display very stale data. It should always be network-first, as that is the desired cache strategy.

The reference screenshot fixes the issue, and I made that locally. I hope this change can be accepted, so I don't need to manually change this when I update the plugin.

**Comment by pradipshende** [comment]
Push changes in Super Progressive Web Apps 2.2.7 version
