### ISSUE TITLE
Manifest file showing wrong logo images link

### ISSUE THREAD

**Issue by 77naveenop** [SuperPWA/Super-Progressive-Web-Apps#379]
The manifest file shows the wrong Logo link which redirects to 404 and the preloader is not working, sometimes it starts working and sometimes shows issues.

Reference ticket -: https://magazine3.in/conversation/81379?folder_id=23

**Comment by akshaywali** [comment]
Issue fixed in following updates
[CTA not showing on homepage #379](https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/ae5ddf870a5a16ef04eb784d84f6d6ad381c8390)
[On iPhone PWA app it gets stuck with preloader when clicking a link t…](https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/7040fd7b778dde6a58c3d0b3d2335156f6eaefb1)
[#379 internal links with target="_blank" show loader with 1-2 seconds](https://github.com/SuperPWA/super-progressive-web-apps-pro/commit/77a74f1ab479151e2fed6180e327760363632003)

**Comment by akshaywali** [comment]
pushed in SuperPWA Pro 1.27
