### ISSUE TITLE
icon update after installation

### ISSUE THREAD

**Issue by accursiodimino** [SuperPWA/Super-Progressive-Web-Apps#456]
hello I installed the application on the phone with a name and an initial icon, then I changed the logo (app icon) and the name but the old icon and name is still displayed on the phone and no update is proposed, like can i force or change the icon without a pwa uninstall and reinstall? Thank you

**Comment by GitStudying** [comment]
Make sure that all your caches are clear, first from the server side. Then make sure that your client/phone cache of the specific site is cleared/refreshed by deleting the sites data in the browser settings or force refresh (but this does not always work I think).
Then if you reinstall you should see updated details and icons.

**Comment by akshaywali** [comment]
@accursiodimino 
This issue is caused by caching. You can follow the below steps to fix the issue.

1.  After changing the logo . Change Service Worker version,  you can find it in advance  tab.
2.  Clear cache in your browser (Chrome/Safari) since PWA actually runs in the browser instance.
3. Also make sure your server side cache is also cleared.

Hope this helps.

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
