### ISSUE TITLE
Bad uninstall, 404 errors

### ISSUE THREAD

**Issue by sturzael** [SuperPWA/Super-Progressive-Web-Apps#49]
Hey guys,

I uninstalled the plugin for testing and debugging purposes and I noticed that in my console I am getting multiple 404 errors when I am logged as **admin** as something is still calling 'superpwa-sw.js'. 

The error repeats itself over if the site is left idling.

I have no idea where this is being called from - I don't believe its an caching issue either.

I also get this message: 'SuperPWA: Current page is excluded from cache'.

This doesn't pose a problem to the visitors as only logged in users see this however I prefer to keep the errors to a minimum anyway, do you know of any fixes to this?

Did I uninstall the plugin wrong? If so can you point me in the right direction of where I can find some documentation on this?

If you want to have a look at the site the URL is: 'https://www.nettl.com.au/'

I don't believe you will see the error as you won't be logged in as admin but maybe you can see something I can't.

Cheers for the help.

![spwa](https://user-images.githubusercontent.com/20013047/41830139-2d183c56-7893-11e8-860b-330e17657305.PNG)

**Comment by josevarghese** [comment]
Hi @sturzael 

Good day and thanks for using SuperPWA. 

Seems like the you haven't cleared the Service Worker which is registered during the testing within your browser. That's why you are noticing those 404 error as those files are deleted during uninstall.

You can easily unregister the service Worker from browser by clicking the **Applications** tab within the **Developer tools** and from the left menu you can see **Service Workers**. Click on it and unregister the **superpwa-sw.js**.

You can also clear the browsing data to easily unregister this file.

Looking forward.

Thanks,
Jose

**Comment by sturzael** [comment]
Thanks for the quick reply.

Didn't even think of that, my bad haha. 

Cheers mate.

**Comment by josevarghese** [comment]
Awesome! Glad to hear that @sturzael 
If you don't mind can you please let me know why you uninstalled it?

**Comment by sturzael** [comment]
Not a plugin related problem - Was having a few big issues with custom scripts and caching - I just uninstalled everything that could even be remotely related at all to try and resolve it.

I use the plugin on a few other sites and will still continue to use it.

**Comment by josevarghese** [comment]
Happy to hear that!
