### ISSUE TITLE
PWA for each page?

### ISSUE THREAD

**Issue by yoske25** [SuperPWA/Super-Progressive-Web-Apps#51]
Hey. I have a website that I use as 'Online Business Card' type of pages. 
Meaning - each one of my clients has a link on my website that is showing their business. 
Is there any way that I can make each page separably and save each one as a unique web app?
(in other words - each page will have its own unique web app)
Is it possible? 
Thank you

**Comment by arunbasillal** [comment]
Hello @yoske25 

I believe @josevarghese replied to the same query over email. 

For completeness, this is not possible in the current iteration. Once the service worker and manifest are made dynamic (#38) this will be possible with the filters that will be then available. 

We are not sure if dynamic files will be the long term implementation, but if that happens, then sure. 

Please follow issue 38 to see how it turns out.

**Comment by arunbasillal** [comment]
@yoske25 SuperPWA 2.0 that was just released features dynamic service worker and manifest. PWA for each page is possible if you filter the manifest and service worker depending on the requesting page. 

- Filter for manifest - https://superpwa.com/codex/superpwa_manifest/
- Filter for service worker - https://superpwa.com/codex/superpwa_sw_template/
- Filter for start url - https://superpwa.com/codex/superpwa_manifest_start_url/

I hope that helps.

**Comment by yoske25** [comment]
Thank u for checking me out and remember me liek 7 months after lol :)
that's one customer service!
Will make sure to look out. thanks!

‫בתאריך יום ה׳, 27 בדצמ׳ 2018 ב-23:45 מאת ‪Arun Basil Lal‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by arunbasillal** [comment]
Haha, you are welcome and glad to hear that.
