### ISSUE TITLE
A2HS display property not working with subfolder

### ISSUE THREAD

**Issue by shabbir-dhangot** [SuperPWA/Super-Progressive-Web-Apps#56]
We have installed SuperPWA for our blog. We are getting auto prompt from browser and its adding into homepage. Below is Manifest URL.

https://stgb2c.turacomobile.com:9443/blog/superpwa-manifest.json

**Problem**
- Clicking on icon not opening as a standalone application. 
- Every time hitting URL is prompting to A2HS. Its already 

Is it happening due to website is in sub--folder? Main Website is having its own manifest. 
Website URL : https://stgb2c.turacomobile.com:9443/blog/
Kindly help to resolve this issue.

**Comment by josevarghese** [comment]
Hi @shabbir-dhangot,

Good day and thanks for using SuperPWA WordPress plugin. I think the issue is because of the 9443 port within the web URL, as the manifest cannot detect that the website is already added as a PWA.

We also noticed that someone already [opened a thread upon WordPress directory ](https://wordpress.org/support/topic/add-to-home-screen-popup-not-showing/) regarding the same website, have you tried changing the Start Page and Offline Page upon our settings page with any other on the same URL mentioned their?

**Comment by Sanjeevsetu** [comment]
Closing the ticket due to inactivity. Still have an issue, Please create a new ticket or contact us.
