### ISSUE TITLE
How to get rid of Super PWA

### ISSUE THREAD

**Issue by coolrecep** [SuperPWA/Super-Progressive-Web-Apps#69]
I'm really bored of bugs that came with this add-on. I've disabled it, removed it but even if I did not intend to use it for my forum software XenForo, PWA fucked it up and keeps messing with it. I do not want to see a superpwa-js app runing for my website, at least until it is completely updated.

Oh BTW, the last bug we encountered was causing the posts to load partially, making only the banner ad visible. You had to do an F5 to load it again...

**Comment by josevarghese** [comment]
Sorry to hear that from @coolrecep, If you have any screenshots regarding the half loaded posts, please do share it here. So that we can have a look over it and help you further.

Our plugin provides a clean uninstall, that's the plugin files will get deleted from the server once you uninstall it. If you are using any caching plugins, don't forget to flush the cache to completely remove it. Also if Cloudflare/any CDN/Server caching is used, don't forget to flush the cache over it too.

Hope that helps. Looking forward.

**Comment by joglomedia** [comment]
He use xenForo, does this plugin support for xenForo or only Wordpress?
